### PR TITLE
Create pt-BR.ts

### PR DESCRIPTION
**Pull request by Krazy-Monkey**
Brazilian Portuguese (pt-BR) language for GTA V Launcher

### CODE REVIEW

**Comment by Krazy-Monkey** [comment]
@moffa13 When will the new language be available in your tool?

**Comment by moffa13** [comment]
@Krazy-Monkey When I'll publish the next release. I'm also going to add the possibility to manually select a language other than OS's default language.

**Comment by moffa13** [comment]
Yes this is what I will do. Should I add pt_BR language also for pt_PT ?

**Comment by Krazy-Monkey** [comment]
No, because Brazilian Portuguese and European European have their differences. Just like American English and British English.

**Comment by moffa13** [comment]
I really don't know but I think it is a good idea to translate the names into the corresponding language.

**Comment by Krazy-Monkey** [comment]
Also add 32x32 flag icons to the corresponding languages ​​and with the name of the author (and the link to your profile), just as it is in OpenIV.

**Comment by moffa13** [comment]
Hi, I did a quite big update which handles translations.
I removed unnecessary ones from .ts files. Can you take a look and finish all translations for your language ?

If you want some help for the meaning of the sentences, ask me.

**Pull request merged**
